apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/app
patches:
  - target:
      kind: Deployment
      name: default-deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: kafka
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/selector/matchLabels/app
        value: kafka
      - op: replace
        path: /spec/template/metadata/labels/app
        value: kafka
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: kafka
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 9092
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1024Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2048Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: wurstmeister/kafka:2.13-2.7.0
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: 127.0.0.1
          # - name: KAFKA_ADVERTISED_PORT
          #   value: "9092"
          # - name: KAFKA_BROKER_ID
          #   value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service:2181
          - name: KAFKA_CREATE_TOPICS
            value: "demo:1:1"
  - target:
      kind: Service
      name: default-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: kafka
      - op: replace
        path: /spec/ports/0/port
        value: 9092
      - op: replace
        path: /spec/ports/0/targetPort
        value: 9092
      - op: replace
        path: /spec/selector/app
        value: kafka