apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/network

patches:
patches:
  - patch: |
      - op: replace
        path: /metadata/name
        value: argocd-ingress
      - op: replace
        path: /metadata/namespace
        value: argocd
      - op: replace
        path: /spec/rules/0/host
        value: staging-argocd.example.com
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: argocd-server
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 8080
    target: 
      kind: Ingress
      name: default-ingress