apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/network
  - ../../../base/app
patches:
  - target:
      kind: Deployment
      name: default-deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: kafka-app-deployment
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/selector/matchLabels/app
        value: kafka-app
      - op: replace
        path: /spec/template/metadata/labels/app
        value: kafka-app
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: kafka-container
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: mrdevopsman/kafka-spring-app:1.0.1
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: KAFKA_BROKER
            value: kafka:9092
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka:9092
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
  - target:
      kind: Service
      name: default-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: kafka-app-service
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8080
      - op: replace
        path: /spec/selector/app
        value: kafka-app
  - target:
      kind: Ingress
      name: default-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: kafka-app-ingress
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/rules/0/host
        value: kafka.example
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: kafka-app-service
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 8080
      - op: add
        path: /metadata/annotations
        value:
          nginx.ingress.kubernetes.io/rewrite-target: /
