apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/osodevops/argocd-gitops-demo.git' 
    targetRevision: jc
    path: overlays/staging
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
