apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/network
  - ../../../base/app
patches:
  - target:
      kind: Deployment
      name: default-deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-deployment
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/selector/matchLabels/app
        value: nginx
      - op: replace
        path: /spec/template/metadata/labels/app
        value: nginx
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: nginx
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: gcr.io/google-samples/hello-app:1.0
  - target:
      kind: Service
      name: default-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-service
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8080
  - target:
      kind: Ingress
      name: default-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-ingress
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/rules/0/host
        value: nginx.example
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: nginx-service
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 8080
