apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/network
  - ../../../base/app
patches:
  - target:
      kind: Deployment
      name: default-deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: python-deployment
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/selector/matchLabels/app
        value: python-app
      - op: replace
        path: /spec/template/metadata/labels/app
        value: python-app
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: python-container
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: python:3.8-slim
      - op: add
        path: /spec/template/spec/containers/0/command
        value: ["sh", "-c"]
      - op: add
        path: /spec/template/spec/containers/0/args
        value: ["pip install flask && echo 'from flask import Flask; app = Flask(__name__); @app.route(\"/\") def hello(): return \"Hello, World!\"; if __name__ == \"__main__\": app.run(host=\"0.0.0.0\", port=8080)' > app.py && python app.py"]
  - target:
      kind: Service
      name: default-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: python-service
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8080
  - target:
      kind: Ingress
      name: default-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: python-ingress
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/rules/0/host
        value: python.example
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: python-service
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 8080
