apiVersion: apps/v1
kind: Deployment
metadata:
  name: points-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: points-service
  template:
    metadata:
      labels:
        app: points-service
    spec:
      containers:
        - image: points-service:local
          imagePullPolicy: Never
          name: points-service
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 1024m
              memory: 2048Mi
            requests:
              cpu: 512m
              memory: 1024Mi